### PR TITLE
fix scroll ngang, fix screen cart mobie

### PR DESCRIPTION
**Pull request by ThanhTa2ngan4**
fix scroll ngang, fix screen cart mobie . Checkd giúp mình @xuanloi1999  @NgnHien  @ngodinhan058

### CODE REVIEW

**Review by NgnHien — DISMISSED** [review]
Checked

**Review by NguyenMinhThiet — DISMISSED** [review]
checked

**Review by NguyenMinhThiet — APPROVED** [review]
checked

**Review by NgnHien — APPROVED** [review]
Checked

**Pull request merged**
