### PR TITLE
Dinhan/related products

### PR DESCRIPTION
**Pull request by ngodinhan058**

### CODE REVIEW

**Comment by ngodinhan058** [comment]
@ThanhTa2ngan4 @NgnHien @xuanloi1999 @NguyenMinhThiet @Minhbinh0206 merge và review giúp tôi

**Review by NgnHien — DISMISSED** [review]
Checked

**Review by NguyenMinhThiet — DISMISSED** [review]
Checked

**Review by NgnHien — DISMISSED** [review]
Checked

**Review by NguyenMinhThiet — APPROVED** [review]
checked

**Pull request closed without merging**
