### PR TITLE
Fix List Brand

### PR DESCRIPTION
**Pull request by NgnHien**

### CODE REVIEW

**Comment by NgnHien** [comment]
@xuanloi1999 @ngodinhan058 @thanhvkl Review And Merge for me

**Comment by NgnHien** [comment]
@xuanloi1999 @ngodinhan058 @thanhvkl review and merge for me

**Review by ngodinhan058 — APPROVED** [review]
checked

**Review by NguyenMinhThiet — APPROVED** [review]
checked

**Pull request merged**
